#!/usr/bin/env bash

RUBY=1.9.3-p0

## Functions
message() {
  echo; echo "$(tput bold)$(tput setaf 2)$@$(tput sgr0)"
}

install_gem(){
  message "$2"
  gem install "$1" --no-rdoc --no-ri
}

install_package(){
  message "$2"
  brew install "$1"
}

install_sqlite(){
  install_package "sqlite" "Installing SQLite..."
  install_gem "sqlite" "Installing SQLite Ruby gem..."
}

install_postgresql() {
  install_package "postgres" "Installing PostgreSQL..."
  install_gem "pg" "Installing PostgreSQL Ruby gem..."
}

install_mysql() {
  install_package "mysql" "Installing MySQL..."
  install_gem "mysql2" "Installing MySQL Ruby gem..."
}

## AMI options
SSH_KEY=0
NGINX=0
RDBMS=""
SHELLRC=""

message "Select your shell configuration file..."
select option in "zshrc" "profile" "bash_profile" "bashrc" "Skip"; do
  if [ "$option" != "Skip" ]; then
    SHELLRC=$option
  fi
  break
done

message "Generate SSH key and copy it to clipboard?"
select option in Yes No; do
  case $option in
    "Yes")
      SSH_KEY=1; break;;
    "No")
      break;;
  esac
done

message "Install Nginx?"
select option in Yes No; do
  case $option in
    "Yes")
      NGINX=1; break;;
    "No")
      break;;
  esac
done

message "Select which RDBMS to install..."
select option in SQLite PostgreSQL MySQL All Skip; do
  case $option in
    "SQLite")
      RDBMS="sqlite"; break;;
    "PostgreSQL")
      RDBMS="postgresql"; break;;
    "MySQL")
      RDBMS="mysql"; break;;
    "All")
      RDBMS="all"; break;;
    "Skip")
      break;;
  esac
done

## Start...
message "Installing..."

## SSH
  if [ "$SSH_KEY" == 1 ]; then
    message "Generating SSH key..."
    [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa
    [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
    open https://github.com/account/ssh
  fi

## rbenv
  message "Installing rbenv..."
    git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
    if [ "$SHELLRC" != "" ] && [ -a "$HOME/.$SHELLRC" ]; then
      message "Configuring ~/.$SHELLRC..."
      echo '
#rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"' >> "$HOME/.$SHELLRC"
      source "$HOME/.$SHELLRC"
    else
      echo; echo "$(tput bold)$(tput setaf 1)Manual Shell configuration or selected file not found...$(tput sgr0)"
    fi

## ruby-build
  message "Installing ruby-build..."
    git clone git://github.com/sstephenson/ruby-build.git
    cd ruby-build
    echo "$(tput bold)$(tput setaf 1)Password required!$(tput sgr0)"
    sudo ./install.sh
    cd ~

## Ruby
  message "Installing Ruby $RUBY..."
    rbenv install $RUBY
    rbenv rehash
    rbenv global $RUBY

## Homebrew
  message "Installing Homebrew..."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/gist/323731)" #https://github.com/mxcl/homebrew/wiki/installation
    brew update
  install_package "ack"         "Installing Ack..."
  install_package "redis"       "Installing Redis..."
  install_package "imagemagick" "Installing ImageMagick..."
  if [ "$NGINX" == 1 ]; then
    install_package "nginx" "Installing Nginx..."
  fi

## Ruby Gems
  message "Updating RubyGems..."
    gem update --system
    gem update
  install_gem "bundler" "Installing Bundler gem..."
  install_gem "rails"   "Installing Rails gem..."
  install_gem "heroku"  "Installing Heroku gem..."
  install_gem "taps"    "Installing Taps gem..."

## RDBMS
  if [ "$RDBMS" == "sqlite" ]; then
    install_sqlite
  elif [ "$RDBMS" == "postgresql" ]; then
    install_postgresql
  elif [ "$RDBMS" == "mysql" ]; then
    install_mysql
  elif [ "$RDBMS" == "all" ]; then
    install_sqlite
    install_postgresql
    install_mysql
  fi

## Restart shell one final time
  if [ "$SHELLRC" != "" ] && [ -a "$HOME/.$SHELLRC" ]; then
    source "$HOME/.$SHELLRC"
  fi

message "Complete!"; echo
